### ISSUE TITLE
Todo List and Contact Info?

### ISSUE THREAD

**Issue by flumf** [nongeneric/ps3emu#1]
Hey there!
I stumbled upon this project and I was wondering if there was a todo list or any way to contact you, as I'm interested in getting it to compile and run, maybe getting it to work on older GPUs as well :)

Cheers,
bin

**Comment by nongeneric** [comment]
Hi,

It's been some time since I last worked on it, so unfortunately there's no real progress being made. I also don't have any particular features planned. It's more like fixing a few bugs here and there and trying to run another game.

Still, there are some short guides I wrote for compiling it and setting it up:

https://rcebits.com/ps3emu/building.html
https://rcebits.com/ps3emu/environment.html
    
I should warn though, that it is of little practical use yet. The project is in its early stages, with only 2 games running.

Anyway, feel free to email me vm@rcebits.com and I'll be happy to help.

**Comment by flumf** [comment]
Sweet,
By any chance, do you have a discord account? Mine is bin#6239.
If you don't I'll just email you :)
